# Work in Progress
consul:
  image: progrium/consul
  volumes:
    - /data
    - /config
    - ./src/test/resources/consul_ui:/ui
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
  command: -server -bootstrap -data-dir /data -ui-dir /ui
